name: Deploy to GitHub Pages

on:
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 23
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: dist/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      timeout-minutes: 3
